### ISSUE TITLE
Sibling library

### ISSUE THREAD

**Issue by pboling** [ticky/ruby-emoji-regex#41]
Hi @ticky - just wanted to let you know about a gem I've just released that is inspired by this gem, called [`gitmoji-regex`](https://github.com/pboling/gitmoji-regex).  It's not a fork. It validates a different set of unicode chars (gitmoji is a tiny subset of emoji), and does it somewhat differently, but some aspects of the library design are taken directly from your work here.  Thanks for creating this!

**Comment by ticky** [comment]
Oh, neat! Glad to have helped with inspiration :)
