### ISSUE TITLE
Could you please help on why this happen when i add ruby-emoji-regex gem from github to my project?

### ISSUE THREAD

**Issue by zw963** [ticky/ruby-emoji-regex#44]
Please check following screenshot.

![image](https://user-images.githubusercontent.com/549126/163706709-91fd5408-197c-40b5-941f-f9131d783bd0.png)

I just add ``gem 'emoji_regex', github: 'ticky/ruby-emoji-regex'`` into my Gemfile 3 weeks ago, i get this error today.

**Comment by pboling** [comment]
Declaring a dependency on `github: 'whatever'` is inherently unstable.  It points to whatever the maintainer sets as their default branch, in the case of this repo that is `develop`, and you are pointing to a moving target: the `HEAD` of that branch.

There is a tag that would allow you to avoid this instability and still retain the (current) bleeding edge you seem to want - `v14.0.0.pre.1`.

Do it like this:
```ruby
gem 'emoji_regex', github: 'ticky/ruby-emoji-regex', tag: 'v14.0.0.pre.1'
```

**Comment by ticky** [comment]
The pre-release is also available on Rubygems: https://rubygems.org/gems/emoji_regex/versions/14.0.0.pre.1 - I'd suggest installing there rather than directly from `develop`!

**Comment by ticky** [comment]
Ah, sorry, I missed the context that you're in China, @pboling's suggestion is probably the right one, in that case.

**Comment by ticky** [comment]
Oh, never mind, it's on the mirror too: https://gems.ruby-china.com/gems/emoji_regex/versions/14.0.0.pre.1

**Comment by zw963** [comment]
Don't know why, can not search out pre release when switch to gems.ruby-china.com.

```rb
╰─ $ gem search -a --prerelease 'emoji_regex'

*** REMOTE GEMS ***

emoji_regex (0.1.1, 0.1.0)

```

But can find it when search on https://rubygems.org

```sh
 ╰─ $ gem search -a --prerelease 'emoji_regex'

*** REMOTE GEMS ***

emoji_regex (14.0.0.pre.1, 3.2.3, 3.2.2, 3.2.1, 3.2.0, 3.0.0, 2.0.0, 1.0.1, 1.0.0, 0.1.1, 0.1.0)
```
