### ISSUE TITLE
Update to v15.0 emojis

### ISSUE THREAD

**Issue by spaghetticode** [ticky/ruby-emoji-regex#46]
Is a new gem release being planned? I think that in order to keep the gem updated this [automated PR](https://github.com/ticky/ruby-emoji-regex/pull/42) should be merged. I'm not familiar with this gem, but I think that running `script/regenerate` and possibly updating specs with new emojis would be needed for a new release. Can you confirm this is the right path? Thanks :)

**Comment by ticky** [comment]
Sorry, this has taken a bit of a back seat as I no longer work somewhere which uses Ruby, or relies on this gem. I'll endeavour to get 14.0.0, 14.1.0 and 15.0.0 out imminently, though!

**Comment by ticky** [comment]
Okay, [v14.0.0](https://github.com/ticky/ruby-emoji-regex/releases/tag/v14.0.0) and [v15.0.0](https://github.com/ticky/ruby-emoji-regex/releases/tag/v15.0.0) are out! Apologies for the delay.
